name: Request Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  request-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Request review
      uses: reviewdog/action-github-review@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: 'tejaswini-simha'  # List of GitHub usernames or teams
        body: 'Please review this pull request.'  # Optional message
